### PR TITLE
updated issue template

### PR DESCRIPTION
**Pull request by StrikerRUS**
### Checklist

- [ ] All new jobs, commands, executors, parameters have descriptions
- [ ] Examples have been added for any significant new features
- [ ] README has been updated, if necessary

### Motivation, issues

Fix GitHub deprecation warning:

image

Refer to the https://github.com/CircleCI-Public/artifactory-orb/pull/17#issuecomment-537965446.

### Description

Happy Orbtoberfest!

### CODE REVIEW

**Comment by gep13** [comment]
@StrikerRUS thank you for taking care of this.  I just went to do this just now, but then I noticed that you had already taken care of it 😄

**Comment by StrikerRUS** [comment]
@gep13 Huh, thank you very much for spotting this issue in other repos!

**Review by KyleTryon — CHANGES_REQUESTED** [review]
Hello, sorry I believe this is now out of date. However, the pull request template still needs to be moved it seems. https://github.com/CircleCI-Public/orb-starter-kit/tree/master/.github

**Comment by StrikerRUS** [comment]
@KyleTryon Yeah, it seems that

**Pull request closed without merging**
