### PR TITLE
Fix grammatical mistake in readme

### LINKED ISSUE #23: Grammatical mistake in readme
### What happened

Grammatical mistake in readme

### Expected behavior

The grammatical mistake should be removed from readme

### PR DESCRIPTION
**Pull request by parammittal16**
### Checklist

- [x] All new jobs, commands, executors, parameters have descriptions
- [x] Examples have been added for any significant new features
- [x] README has been updated, if necessary

### Description
Fixes #23 Improve Readme by removing errors.

### CODE REVIEW

**Comment by glenjarvis** [comment]
@parammittal16 These changes look good to me.

**Comment by KyleTryon** [comment]
Hello and thank you. If the conflicts can be resolved we would be happy to merge.

**Comment by parammittal16** [comment]
@KyleTryon resolved the merge conflicts. plz review

**Review by KyleTryon — APPROVED** [review]

**Pull request merged**
