### PR TITLE
Correct verb tense in README

### PR DESCRIPTION
**Pull request by glenjarvis**
### Checklist

- [x] All new jobs, commands, executors, parameters have descriptions
- [x] Examples have been added for any significant new features
- [x] README has been updated, if necessary

### Motivation, issues

This is a minor correction to a typo (verb tense) in README.

### Description

Correct verb tense in README

### CODE REVIEW

**Comment by glenjarvis** [comment]
Rebasing to avoid conflict. I will close this PR momentarily with a new PR to fix.

**Comment by FelicianoTech** [comment]
You can rebase in this PR. Just `git push -f` after the rebase.

**Comment by glenjarvis** [comment]
Closing in favor of https://github.com/CircleCI-Public/orb-starter-kit/pull/13

**Comment by glenjarvis** [comment]
@felicianotech I didn't see your last note about asking for a force push until now (otherwise I would have). A new PR has been created and this one closed: https://github.com/CircleCI-Public/orb-starter-kit/pull/13

If I create any other PRs and we see a conflict again, I can force push per your process.

**Pull request closed without merging**
